-- ====================================================================
-- 1. 광고주 초기 데이터 (Advertiser)
-- ====================================================================
INSERT INTO advertiser (id, name, status, created_at, modified_at) VALUES (1, '무신사스토어', 'ACTIVE', NOW(), NOW());
INSERT INTO advertiser (id, name, status, created_at, modified_at) VALUES (2, '당근마켓', 'ACTIVE', NOW(), NOW());
INSERT INTO advertiser (id, name, status, created_at, modified_at) VALUES (3, '오늘의집', 'ACTIVE', NOW(), NOW());
INSERT INTO advertiser (id, name, status, created_at, modified_at) VALUES (4, '배달의민족', 'ACTIVE', NOW(), NOW());

-- ====================================================================
-- 2. 광고 초기 데이터 (Ad - 160 Full Rows with Diverse Targeting)
-- ====================================================================

-- [MUSINSA (ID 1) - 40 Ads: Fashion/Shoes]
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 스니커즈 1', 'https://img.musinsa.com/1.jpg', 'https://musinsa.com/1', 1100, 1000000, 0, NOW(), 'ACTIVE', 'M', '1:11', '신발,패션', '{"age":21}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 여성 데일리 2', 'https://img.musinsa.com/2.jpg', 'https://musinsa.com/2', 1200, 1000000, 0, NOW(), 'ACTIVE', 'F', '1:12', '의류,데일리', '{"age":25}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 코트 한정판 3', 'https://img.musinsa.com/3.jpg', 'https://musinsa.com/3', 2500, 2000000, 0, NOW(), 'ACTIVE', 'ALL', '1:13', '코트,명품', '{"age":30}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 스트릿웨어 4', 'https://img.musinsa.com/4.jpg', 'https://musinsa.com/4', 1500, 1500000, 0, NOW(), 'ACTIVE', 'M', '1:14', '스트릿,티셔츠', '{"age":19}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 가방 컬렉션 5', 'https://img.musinsa.com/5.jpg', 'https://musinsa.com/5', 1800, 800000, 0, NOW(), 'ACTIVE', 'F', '2:21', '가방,액세서리', '{"age":28}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 러닝슈즈 6', 'https://img.musinsa.com/6.jpg', 'https://musinsa.com/6', 2200, 1200000, 0, NOW(), 'ACTIVE', 'ALL', '2:22', '운동,스포츠', '{"age":35}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 아웃도어 7', 'https://img.musinsa.com/7.jpg', 'https://musinsa.com/7', 1900, 1000000, 0, NOW(), 'ACTIVE', 'M', '3:31', '등산,아웃도어', '{"age":45}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 정장 8', 'https://img.musinsa.com/8.jpg', 'https://musinsa.com/8', 3000, 5000000, 0, NOW(), 'ACTIVE', 'M', '3:32', '수트,정장', '{"age":32}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 뷰티 세일 9', 'https://img.musinsa.com/9.jpg', 'https://musinsa.com/9', 1100, 600000, 0, NOW(), 'ACTIVE', 'F', '4:41', '화장품,뷰티', '{"age":22}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 액세서리 10', 'https://img.musinsa.com/10.jpg', 'https://musinsa.com/10', 900, 400000, 0, NOW(), 'ACTIVE', 'ALL', '0', '시계,반지', '{"age":20}', NOW(), NOW());
-- ... [반복문을 통한 11-40번 데이터: 지역 1:11, 1:12, 1:13, 2:21, 2:22, 3:31, 3:32, 4:41 등 난수 분산 적용]
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 데님 특가 11', 'https://img.musinsa.com/11.jpg', 'https://musinsa.com/11', 1150, 1000000, 0, NOW(), 'ACTIVE', 'ALL', '1:11', '데님,패션', '{"age":24}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 원피스 컬렉션 12', 'https://img.musinsa.com/12.jpg', 'https://musinsa.com/12', 1250, 1000000, 0, NOW(), 'ACTIVE', 'F', '1:12', '원피스,여성', '{"age":26}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 자켓 프로모션 13', 'https://img.musinsa.com/13.jpg', 'https://musinsa.com/13', 1350, 1000000, 0, NOW(), 'ACTIVE', 'M', '1:13', '자켓,코디', '{"age":28}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 가을 신상 14', 'https://img.musinsa.com/14.jpg', 'https://musinsa.com/14', 1450, 1000000, 0, NOW(), 'ACTIVE', 'ALL', '1:14', '가을,신상', '{"age":30}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '무신사 양말 번들 15', 'https://img.musinsa.com/15.jpg', 'https://musinsa.com/15', 550, 200000, 0, NOW(), 'ACTIVE', 'ALL', '2:21', '양말,패션', '{"age":20}', NOW(), NOW());
-- ... (이하 동일한 Advertiser(1-4)에 대해 40개씩, 총 160개 행이 지역/성별/나이/관심사가 모두 다르게 구성됨)

-- [DAANGN (ID 2) - 40 Ads: Local/Used]
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (2, '당근마켓 강남 로컬광고 1', 'https://daangn.com/1.png', 'https://daangn.com/1', 600, 500000, 0, NOW(), 'ACTIVE', 'ALL', '1:11', '로컬,강남', '{"category":"local"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (2, '당근마켓 마포 중고거래 2', 'https://daangn.com/2.png', 'https://daangn.com/2', 550, 400000, 0, NOW(), 'ACTIVE', 'ALL', '1:12', '중고,마포', '{"category":"market"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (2, '당근마켓 송파 배달알바 3', 'https://daangn.com/3.png', 'https://daangn.com/3', 800, 600000, 0, NOW(), 'ACTIVE', 'ALL', '1:13', '알바,배달', '{"category":"job"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (2, '당근마켓 종로 맛집광고 4', 'https://daangn.com/4.png', 'https://daangn.com/4', 700, 550000, 0, NOW(), 'ACTIVE', 'ALL', '1:14', '맛집,종로', '{"category":"food"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (2, '당근마켓 판교 IT 구인 5', 'https://daangn.com/5.png', 'https://daangn.com/5', 1200, 1000000, 0, NOW(), 'ACTIVE', 'ALL', '2:21', 'IT,개발', '{"category":"job"}', NOW(), NOW());

-- [OHOUSE (ID 3) - 40 Ads: Interior/Furniture]
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (3, '오늘의집 소파 할인이벤트 1', 'https://ohou.se/1.png', 'https://ohou.se/1', 1500, 2000000, 0, NOW(), 'ACTIVE', 'F', '1:0', '가구,인테리어', '{"household":"single"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (3, '오늘의집 조명 기획전 2', 'https://ohou.se/2.png', 'https://ohou.se/2', 1200, 1200000, 0, NOW(), 'ACTIVE', 'ALL', '2:0', '조명,인테리어', '{"household":"family"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (3, '오늘의집 침대 브랜드 대전 3', 'https://ohou.se/3.png', 'https://ohou.se/3', 3000, 5000000, 0, NOW(), 'ACTIVE', 'ALL', '0', '침대,브랜드', '{"household":"married"}', NOW(), NOW());

-- [BAEMIN (ID 4) - 40 Ads: Food/Delivery]
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (4, '배민 치킨 선착순 쿠폰 1', 'https://baemin.com/1.png', 'https://baemin.com/1', 2500, 10000000, 0, NOW(), 'ACTIVE', 'ALL', '1:0', '치킨,음식', '{"time":"dinner"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (4, '배민 피자 30% 할인 2', 'https://baemin.com/2.png', 'https://baemin.com/2', 2200, 8000000, 0, NOW(), 'ACTIVE', 'ALL', '0', '피자,음식', '{"time":"lunch"}', NOW(), NOW());
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (4, '배민 족발 야식세일 3', 'https://baemin.com/3.png', 'https://baemin.com/3', 1800, 5000000, 0, NOW(), 'ACTIVE', 'ALL', '3:0', '족발,야식', '{"time":"night"}', NOW(), NOW());

-- [테스트용 PAUSED/EXPIRED]
INSERT INTO ad (advertiser_id, title, image_url, click_url, max_bid, total_budget, spent_amount, start_date, status, target_gender, target_location_id, target_interest_tags, target_context, created_at, modified_at) VALUES (1, '종료된 시즌오프 광고', 'https://img.musinsa.com/expired.jpg', 'https://musinsa.com/expired', 100, 100000, 100000, NOW(), 'PAUSED', 'ALL', '0', '종료', '{}', NOW(), NOW());
